'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5466
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("cargo3.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _Property() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Property", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ARW01RT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ARW01RT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ARW05DN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ARW05DN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ARW05UP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ARW05UP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CLOCK02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CLOCK02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DISKS04() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DISKS04", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DRAG3PG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DRAG3PG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DRAG3PG1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DRAG3PG1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property GRAPH15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GRAPH15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property INFO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("INFO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property KEY04() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("KEY04", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MDICHILD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MDICHILD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MISC17B() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MISC17B", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MOUSE02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MOUSE02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property OPENFOLD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OPENFOLD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PORTRAIT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PORTRAIT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property W95MBX01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("W95MBX01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property W95MBX02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("W95MBX02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property W95MBX04() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("W95MBX04", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
