'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3603
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Priority.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CREATE TABLE ABC &apos;ABC&apos; 0
        '''PART (INT,13,&apos;Part (ID)&apos;)
        '''QUANT (REAL,13,2,&apos;Qty (Factory Units)&apos;)
        '''PRICE (REAL,13,2,&apos;Unit Price&apos;)
        '''QPRICE (REAL,16,2,&apos;Extended Price&apos;)
        '''PERCENT (REAL,8,2,&apos;% Total Issue&apos;)
        '''ACCPERCENT (REAL,8,2,&apos;Total Accumulated %&apos;)
        '''CLASS (CHAR,1,&apos;Class&apos;)
        '''OLD (CHAR,1,&apos;Standard Class&apos;)
        '''UNIQUE (PART)
        '''NONUNIQUE (CLASS)
        ''';
        '''
        '''CREATE TABLE ABILITIES &apos;Abilities&apos; 0
        '''ABILITY (INT,13,&apos;Ability (ID)&apos;)
        '''ABILITYCODE (CHAR,3,&apos;Qualification Code&apos;)
        '''ABILITYDES (CHAR,32,&apos;Qualification Desc.&apos;)
        '''AUTOUNIQUE (ABIL [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property TableDictionary() As String
            Get
                Return ResourceManager.GetString("TableDictionary", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
