'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5466
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.5466.
'
Namespace PriWebSVC
    
    '''<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ServiceSoap", [Namespace]:="http://priwebsvc.ntsa.org.uk/")>  _
    Partial Public Class Service
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://baldrick:8080/service.asmx"
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://priwebsvc.ntsa.org.uk/LoadData", RequestNamespace:="http://priwebsvc.ntsa.org.uk/", ResponseNamespace:="http://priwebsvc.ntsa.org.uk/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function LoadData(ByVal SerialData As String) As Boolean
            Dim results() As Object = Me.Invoke("LoadData", New Object() {SerialData})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Function BeginLoadData(ByVal SerialData As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("LoadData", New Object() {SerialData}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndLoadData(ByVal asyncResult As System.IAsyncResult) As Boolean
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://priwebsvc.ntsa.org.uk/GetData", RequestNamespace:="http://priwebsvc.ntsa.org.uk/", ResponseNamespace:="http://priwebsvc.ntsa.org.uk/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetData(ByVal SQL As String, ByVal Env As String) As String
            Dim results() As Object = Me.Invoke("GetData", New Object() {SQL, Env})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginGetData(ByVal SQL As String, ByVal Env As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetData", New Object() {SQL, Env}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetData(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://priwebsvc.ntsa.org.uk/SaveSignature", RequestNamespace:="http://priwebsvc.ntsa.org.uk/", ResponseNamespace:="http://priwebsvc.ntsa.org.uk/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SaveSignature(ByVal SerialData As String) As String
            Dim results() As Object = Me.Invoke("SaveSignature", New Object() {SerialData})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginSaveSignature(ByVal SerialData As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SaveSignature", New Object() {SerialData}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndSaveSignature(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
    End Class
End Namespace
