  
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <link rel="stylesheet" href="http://soloncopy.test/css/normalize.min.css" />
    <link rel="stylesheet" href="http://soloncopy.test/css/main.css" />
    <link rel="stylesheet" href="http://soloncopy.test/css/html5reset.css" />
    <link rel="stylesheet" href="http://soloncopy.test/css/pxtoem.css" />
    <link rel="stylesheet" href="http://soloncopy.test/css/970_5_10_10.css" />
    <link rel="stylesheet" href="http://soloncopy.test/css/solon.css" />
    <link rel="stylesheet" href="http://soloncopy.test/css/sites.css" />
    <!--[if IE 7]>
    <link rel="stylesheet" href="~/css/ie7.css">
    <![endif]-->

    <!--[if IE 8]>
    <link rel="stylesheet" href="~/css/ie8.css">
    <![endif]-->

      <script type="text/javascript" src="ckeditor/ckeditor.js"></script>
    <script src="ckeditor/_samples/sample.js" type="text/javascript"></script>
    <link href="ckeditor/_samples/sample.css" rel="stylesheet" type="text/css"  />

    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->

    <script src="js/vendor/modernizr-custom-2.6.2.js?v=1"></script>

      <link rel="stylesheet" href="css/nivo-slider.css" />
      <link rel="stylesheet" href="css/nivo-slider-theme/solon/solon.css" />
      <link rel="stylesheet" href="css/nivo-slider-theme/solon-overlay/solon-overlay.css" />
      <link rel="stylesheet" href="css/nivo-slider-theme/solon-below/solon-below.css" />

<script>

</script>